"use client";
import {useMemo,useState} from "react";
import {ArrowLeft,ArrowRight,BadgeCheck,Check,Clapperboard,Copy,Download,Film,Gauge,Mic,Save,Search,ShieldCheck,Sparkles,Upload,WandSparkles,X} from "lucide-react";
import Studio from "./studio";
type Status="VERIFIED"|"PARTIAL"|"REVIEW";
type Scene={id:string;work:string;original:string;year:number;type:string;genres:string[];title:string;description:string;relation:string[];situation:string[];emotion:string[];place:string[];weather:string[];props:string[];action:string[];direction:string[];status:Status;source:string;sourceLabel:string};
const db:Scene[]=[
 {id:"classic",work:"클래식",original:"The Classic",year:2003,type:"영화",genres:["로맨스","멜로"],title:"빗속을 함께 달리는 장면",description:"갑작스러운 비를 피해 두 사람이 옷을 함께 받쳐 들고 달리며 가까워지는 장면.",relation:["첫사랑","남녀"],situation:["비 피하기","함께 달리기"],emotion:["달달함","설렘","아련함"],place:["학교","거리"],weather:["비"],props:["옷","가방"],action:["달리기","비 막아주기"],direction:["몽타주","음악 중심"],status:"VERIFIED",source:"https://www.koreanfilm.or.kr/eng/films/index/filmsView.jsp?movieCd=20030046",sourceLabel:"KOFIC 작품 정보"},
 {id:"wolf",work:"늑대의 유혹",original:"Romance of Their Own",year:2004,type:"영화",genres:["로맨스","청춘"],title:"우산 속 첫 만남",description:"비 오는 날 우산 아래에서 인물들이 마주치며 관계가 시작되는 대표 장면.",relation:["삼각관계","첫 만남"],situation:["우산 아래","첫 만남"],emotion:["달달함","설렘"],place:["거리"],weather:["비"],props:["우산"],action:["우산 씌워주기","눈맞춤"],direction:["클로즈업","슬로 모션"],status:"PARTIAL",source:"https://www.koreanfilm.or.kr/eng/films/index/filmsView.jsp?movieCd=20040616",sourceLabel:"KOFIC 작품 정보 · 장면 출처 검토 필요"},
 {id:"singing",work:"사랑은 비를 타고",original:"Singin’ in the Rain",year:1952,type:"영화",genres:["뮤지컬","로맨스"],title:"빗속의 노래와 춤",description:"주인공이 밤거리의 비 속에서 우산을 들고 기쁨을 노래하고 춤추는 장면.",relation:["연인"],situation:["행복한 귀가","빗속 춤"],emotion:["행복","설렘"],place:["밤거리"],weather:["비","밤"],props:["우산","가로등"],action:["노래","춤"],direction:["롱테이크","뮤지컬"],status:"VERIFIED",source:"https://www.tcm.com/tcmdb/title/90162/singin-in-the-rain",sourceLabel:"TCM 작품·장면 자료"},
 {id:"notebook",work:"노트북",original:"The Notebook",year:2004,type:"영화",genres:["로맨스","멜로"],title:"빗속의 재회와 고백",description:"오랜 오해 끝에 빗속에서 다시 마주한 두 사람이 감정을 솔직하게 터뜨리는 장면.",relation:["연인","재회"],situation:["고백","재회"],emotion:["격정","설렘","감동"],place:["호숫가","거리"],weather:["비"],props:["보트"],action:["고백","포옹"],direction:["클로즈업","빗속 연출"],status:"PARTIAL",source:"https://www.warnerbros.com/movies/notebook",sourceLabel:"Warner Bros. 작품 정보 · 장면 검토 필요"},
 {id:"lalaland",work:"라라랜드",original:"La La Land",year:2016,type:"영화",genres:["뮤지컬","로맨스"],title:"언덕 위의 춤",description:"해 질 무렵 도시가 내려다보이는 언덕에서 두 사람이 밀고 당기며 함께 춤추는 장면.",relation:["연인","첫 만남"],situation:["데이트","감정 변화"],emotion:["설렘","달달함"],place:["언덕","도시"],weather:["노을"],props:["구두","가로등"],action:["춤","눈맞춤"],direction:["롱테이크","실루엣"],status:"PARTIAL",source:"https://www.lionsgate.com/movies/la-la-land",sourceLabel:"Lionsgate 작품 정보 · 장면 검토 필요"},

 {id:"goblin",work:"도깨비",original:"Guardian: The Lonely and Great God",year:2016,type:"드라마",genres:["판타지","로맨스"],title:"비 오는 날의 첫 만남",description:"비가 내리는 거리에서 두 인물이 운명처럼 마주하며 관계의 시작을 알리는 장면.",relation:["운명","첫 만남"],situation:["첫 만남"],emotion:["신비","설렘"],place:["거리"],weather:["비","밤"],props:["우산"],action:["눈맞춤","대화"],direction:["슬로 모션","역광"],status:"PARTIAL",source:"https://tvn.cjenm.com/ko/dokebi/",sourceLabel:"tvN 작품 정보 · 장면 검토 필요"},
 {id:"crashlanding",work:"사랑의 불시착",original:"Crash Landing on You",year:2019,type:"드라마",genres:["로맨스","코미디"],title:"장터에서 다시 만난 두 사람",description:"낯선 곳에서 헤어진 두 사람이 사람들 사이에서 서로를 찾아 다시 만나는 장면.",relation:["연인","보호자"],situation:["재회","위기"],emotion:["안도","설렘","감동"],place:["장터","마을"],weather:["밤"],props:["촛불"],action:["찾아가기","눈맞춤"],direction:["군중 연출","클로즈업"],status:"PARTIAL",source:"https://tvn.cjenm.com/ko/cloy/",sourceLabel:"tvN 작품 정보 · 장면 검토 필요"},
 {id:"2521",work:"스물다섯 스물하나",original:"Twenty Five Twenty One",year:2022,type:"드라마",genres:["청춘","로맨스"],title:"분수대 앞의 청춘",description:"힘든 현실을 잠시 잊고 두 청춘이 분수대에서 장난치며 서로에게 웃음을 되찾아 주는 장면.",relation:["친구","첫사랑"],situation:["위로","장난"],emotion:["청춘","행복","설렘"],place:["학교","분수대"],weather:["밤"],props:["동전"],action:["달리기","웃기"],direction:["몽타주","음악 중심"],status:"PARTIAL",source:"https://tvn.cjenm.com/ko/twentyfivetwentyone/",sourceLabel:"tvN 작품 정보 · 장면 검토 필요"},
 {id:"wooyoungwoo",work:"이상한 변호사 우영우",original:"Extraordinary Attorney Woo",year:2022,type:"드라마",genres:["휴먼","로맨스"],title:"회전문을 통과하는 두 사람",description:"회전문 앞에서 어려움을 겪는 주인공에게 상대가 리듬을 알려 주며 함께 통과하는 장면.",relation:["동료","연인"],situation:["도움","첫 교감"],emotion:["따뜻함","설렘"],place:["회사","로비"],weather:[],props:["회전문"],action:["손짓","함께 걷기"],direction:["반복 리듬","미디엄숏"],status:"PARTIAL",source:"https://ena.skylifetv.co.kr/bbs/board.php?bo_table=skydrama&wr_id=113",sourceLabel:"ENA 작품 정보 · 장면 검토 필요"},
 {id:"sun",work:"태양의 후예",original:"Descendants of the Sun",year:2016,type:"드라마",genres:["로맨스","액션"],title:"와인 키스",description:"서로의 마음을 숨기던 두 사람이 와인을 사이에 두고 갑작스럽게 가까워지는 장면.",relation:["연인","동료"],situation:["고백","감정 확인"],emotion:["설렘","긴장"],place:["숙소"],weather:["밤"],props:["와인"],action:["키스","눈맞춤"],direction:["클로즈업","정적"],status:"PARTIAL",source:"https://program.kbs.co.kr/2tv/drama/sun/pc/index.html",sourceLabel:"KBS 작품 정보 · 장면 검토 필요"},

 {id:"pride",work:"오만과 편견",original:"Pride and Prejudice",year:1813,type:"고전문학",genres:["로맨스","풍속"],title:"다아시의 두 번째 청혼",description:"편견과 오해를 넘어 두 사람이 서로의 진심을 확인하는 결정적인 고백 장면.",relation:["연인"],situation:["고백","화해"],emotion:["설렘","감동"],place:["시골길"],weather:["새벽"],props:["편지"],action:["고백","산책"],direction:["대화 중심"],status:"VERIFIED",source:"https://www.gutenberg.org/ebooks/1342",sourceLabel:"Project Gutenberg 원문"},
 {id:"romeo",work:"로미오와 줄리엣",original:"Romeo and Juliet",year:1597,type:"고전문학",genres:["비극","로맨스"],title:"발코니 아래의 사랑 고백",description:"밤의 정원에서 두 연인이 집안의 갈등을 넘어 서로의 사랑을 확인하는 장면.",relation:["연인"],situation:["비밀 고백"],emotion:["설렘","비극"],place:["정원","발코니"],weather:["밤"],props:["발코니"],action:["고백","맹세"],direction:["독백","대화"],status:"VERIFIED",source:"https://www.gutenberg.org/ebooks/1513",sourceLabel:"Project Gutenberg 원문"},
 {id:"littlewomen",work:"작은 아씨들",original:"Little Women",year:1868,type:"고전문학",genres:["성장","가족"],title:"조가 로리의 청혼을 거절하는 장면",description:"오랜 친구의 고백 앞에서 조가 자신의 진심과 원하는 삶을 솔직하게 말하는 장면.",relation:["친구","가족"],situation:["고백","거절"],emotion:["아련함","진지"],place:["들판"],weather:[],props:["편지"],action:["고백","이별"],direction:["대화 중심"],status:"VERIFIED",source:"https://www.gutenberg.org/ebooks/514",sourceLabel:"Project Gutenberg 원문"},
 {id:"gatsby",work:"위대한 개츠비",original:"The Great Gatsby",year:1925,type:"고전문학",genres:["비극","로맨스"],title:"녹색 불빛을 바라보는 개츠비",description:"개츠비가 물 건너편의 녹색 불빛을 바라보며 닿지 않는 꿈과 사랑을 갈망하는 장면.",relation:["옛 연인"],situation:["기다림","회상"],emotion:["아련함","고독"],place:["바다","저택"],weather:["밤"],props:["녹색 불빛"],action:["바라보기"],direction:["상징","독백"],status:"VERIFIED",source:"https://www.gutenberg.org/ebooks/64317",sourceLabel:"Project Gutenberg 원문"},
 {id:"christmascarol",work:"크리스마스 캐럴",original:"A Christmas Carol",year:1843,type:"고전문학",genres:["판타지","교훈"],title:"크리스마스 아침의 변화",description:"과거와 현재, 미래를 본 스크루지가 새 아침을 맞아 사람들에게 온정을 베푸는 장면.",relation:["이웃","가족"],situation:["화해","변화"],emotion:["감동","행복"],place:["거리","집"],weather:["눈","아침"],props:["선물","칠면조"],action:["선물","인사"],direction:["대조","몽타주"],status:"VERIFIED",source:"https://www.gutenberg.org/ebooks/46",sourceLabel:"Project Gutenberg 원문"},

 {id:"spirited",work:"센과 치히로의 행방불명",original:"Spirited Away",year:2001,type:"애니메이션",genres:["판타지","성장"],title:"기차를 타고 물 위를 건너는 장면",description:"치히로가 고요한 수면 위를 달리는 기차에 올라 목적지를 향해 나아가는 장면.",relation:["친구","동료"],situation:["여행","결심"],emotion:["아련함","평온"],place:["기차","바다"],weather:["노을"],props:["기차표"],action:["여행","바라보기"],direction:["롱테이크","음악 중심"],status:"PARTIAL",source:"https://www.ghibli.jp/works/chihiro/",sourceLabel:"스튜디오 지브리 작품 정보 · 장면 검토 필요"},
 {id:"howl",work:"하울의 움직이는 성",original:"Howl's Moving Castle",year:2004,type:"애니메이션",genres:["판타지","로맨스"],title:"하늘을 걷는 첫 만남",description:"하울이 소피의 손을 잡고 사람들 위로 가볍게 걸어 올라가며 위기에서 벗어나는 장면.",relation:["첫 만남","연인"],situation:["구조","첫 만남"],emotion:["설렘","신비"],place:["마을","하늘"],weather:["낮"],props:["모자"],action:["손잡기","하늘 걷기"],direction:["공중 연출","와이드숏"],status:"PARTIAL",source:"https://www.ghibli.jp/works/howl/",sourceLabel:"스튜디오 지브리 작품 정보 · 장면 검토 필요"},
 {id:"yourname",work:"너의 이름은.",original:"Your Name.",year:2016,type:"애니메이션",genres:["판타지","로맨스"],title:"황혼의 계단에서 마주한 두 사람",description:"시간과 기억을 넘어 두 사람이 계단에서 다시 마주하고 이름을 묻는 장면.",relation:["운명","연인"],situation:["재회","기억"],emotion:["아련함","설렘","감동"],place:["계단","도시"],weather:["노을"],props:["끈"],action:["뒤돌아보기","질문"],direction:["교차 편집","클로즈업"],status:"PARTIAL",source:"https://www.kiminona.com/",sourceLabel:"공식 작품 사이트 · 장면 검토 필요"},
 {id:"frozen",work:"겨울왕국",original:"Frozen",year:2013,type:"애니메이션",genres:["판타지","뮤지컬"],title:"얼음 궁전을 세우는 장면",description:"엘사가 홀로 설산을 오르며 자신의 힘을 받아들이고 거대한 얼음 궁전을 만드는 장면.",relation:["자매"],situation:["자기 발견","해방"],emotion:["해방","웅장함"],place:["설산","궁전"],weather:["눈","밤"],props:["얼음 왕관"],action:["노래","마법"],direction:["뮤지컬","변신 몽타주"],status:"PARTIAL",source:"https://movies.disney.com/frozen",sourceLabel:"Disney 공식 작품 정보 · 장면 검토 필요"},
 {id:"tangled",work:"라푼젤",original:"Tangled",year:2010,type:"애니메이션",genres:["판타지","로맨스"],title:"등불이 떠오르는 호수",description:"라푼젤과 플린이 작은 배 위에서 수많은 등불을 바라보며 마음을 확인하는 장면.",relation:["연인"],situation:["데이트","감정 확인"],emotion:["달달함","설렘","감동"],place:["호수","배"],weather:["밤"],props:["등불","보트"],action:["노래","눈맞춤"],direction:["와이드숏","빛 연출"],status:"PARTIAL",source:"https://movies.disney.com/tangled",sourceLabel:"Disney 공식 작품 정보 · 장면 검토 필요"}
];
const axes:Record<string,string[]>={"작품 종류":["영화","드라마","소설","고전문학","동화","애니메이션"],"장르":["로맨스","청춘","코미디","판타지","뮤지컬"],"감정":["달달함","설렘","아련함","행복","감동"],"상황":["첫 만남","고백","재회","비 피하기","함께 달리기"],"관계":["첫사랑","연인","친구","삼각관계"],"장소":["학교","거리","밤거리","바다","카페"],"환경/날씨":["비","눈","밤","노을"],"핵심 소품":["우산","가로등","편지","선물"],"행동":["우산 씌워주기","달리기","눈맞춤","춤"],"연출":["클로즈업","슬로 모션","몽타주","롱테이크"]};
const steps=["명작 SCENE","SCENE MATCH","원작 느낌","캐릭터·팬","STORY ENGINE","4·6컷 편집","완성작"],styles=["달달","코믹","병맛","감동","짓궂음","진지","게임","방송","청춘","영화적"];
const cn=(...v:(string|false|undefined)[])=>v.filter(Boolean).join(" ");
const hits=(s:Scene,sel:string[])=>sel.filter(x=>JSON.stringify(s).includes(x));
const calc=(s:Scene,sel:string[])=>sel.length?Math.min(98,Math.round((hits(s,sel).length/sel.length)*88+10)):0;
function makeStory(s:Scene,style:string,feel:number,fan:string,char:string,cut:4|6){const prop=s.props[0]||"작은 선물",place=s.place[0]||"방송국",action=s.action[0]||"마음을 전하기",core=feel>66?`${s.emotion[0]} 감정과 ‘${prop}’ 상징을 남긴`:"핵심 감정만 남기고 방송 돌발 미션으로 바꾼";return{title:`${fan||"팬"}과 ${prop}의 약속`,logline:`${style} 분위기로 재해석한 ${s.work} 모티프 방셀`,lines:[`${fan||"팬"}이 ${place}에서 특별한 미션을 받는다.`,`${char||"스트리머"}가 ${prop}을 들고 예상 밖의 방식으로 나타난다.`,`둘은 ${core} 장면 속에서 함께 ${action}에 도전한다.`,`${char||"스트리머"}: “오늘만큼은 별풍선 말고, 네가 주인공이야.”`,`작은 실수로 긴장이 풀리고 둘 사이에 웃음이 터진다.`,`마지막 화면에 ‘다음 장면도 함께’라는 메시지가 남는다.`].slice(0,cut),quality:{캐릭터다움:18,대사:18,창의성:14,개인화:13,감정흐름:9,연상성:9,Warudo:5,완결성:5}}}
export function LegacyHome(){
 const [step,setStep]=useState(0),[query,setQuery]=useState("비 오는 날 남자가 여자에게 우산을 씌워주는 달달한 영화"),[sel,setSel]=useState(["영화","비","달달함"]),[picked,setPicked]=useState<Scene|null>(null),[feel,setFeel]=useState(72),[style,setStyle]=useState("달달"),[fan,setFan]=useState("JW"),[char,setChar]=useState("루미"),[cut,setCut]=useState<4|6>(6),[lines,setLines]=useState<string[]>([]),[saved,setSaved]=useState(false),[toast,setToast]=useState("");
 const ranked=useMemo(()=>db.map(scene=>({scene,score:calc(scene,sel)})).sort((a,b)=>b.score-a.score),[sel]);
 const story=useMemo(()=>picked?makeStory(picked,style,feel,fan,char,cut):null,[picked,style,feel,fan,char,cut]);
 const note=(x:string)=>{setToast(x);setTimeout(()=>setToast(""),1800)},toggle=(x:string)=>setSel(a=>a.includes(x)?a.filter(v=>v!==x):[...a,x]);
 const save=()=>{localStorage.setItem("bangsel-vslice",JSON.stringify({fan,char,cut,lines,scene:picked?.id,style,feel}));setSaved(true);note("현재 기기에 프로젝트를 저장했습니다.")};
 return <main className="min-h-screen bg-[#070b14] text-slate-100">
  <header><button onClick={()=>setStep(0)} className="brand"><span><Clapperboard/></span><b>방셀 <i>STORY STUDIO</i><small>Verified Scene Workflow</small></b></button><div className="header-status"><Badge s="VERIFIED"/><span className="badge review"><Sparkles/>AI provider 미연결</span></div><button className="ghost" onClick={save}><Save/>{saved?"저장됨":"프로젝트 저장"}</button></header>
  <div className="progress"><i style={{width:`${(step+1)/steps.length*100}%`}}/></div>
  <div className="shell"><aside><p>PRODUCTION FLOW</p>{steps.map((x,i)=><button key={x} onClick={()=>i<=step&&setStep(i)} className={cn("flow",step===i&&"active",i<step&&"done")}><span>{i<step?<Check/>:i+1}</span><b>{x}</b></button>)}<div className="pipeline"><b>검색 파이프라인</b><p>1. 검색 조건 추출</p><p>2. 실제 작품·장면 확인</p><p>3. 유사도 계산</p><p>4. 검증 결과 추천</p></div></aside>
  <section className="content">
   {step===0&&<><Top title="어떤 명장면을 찾고 있나요?" desc="AI의 기억이 아니라 검증된 작품·장면 레코드에서 조건이 가장 가까운 결과를 찾습니다."/><h2>🔥 인기 있는 명장면</h2><div className="popular">{db.map((s,i)=><article key={s.id}><em>0{i+1}</em><Badge s={s.status}/><b>{s.work}</b><p>{s.title}</p></article>)}</div><div className="search"><Search/><input value={query} onChange={e=>setQuery(e.target.value)}/><button onClick={()=>{setStep(1);note(`${db.length}개 검증 레코드에서 계산했습니다.`)}}>실제 장면 찾기 <ArrowRight/></button></div><div className="chips">{sel.map(x=><button key={x} onClick={()=>toggle(x)}>{x}<X/></button>)}</div><div className="axes">{Object.entries(axes).map(([k,v])=><div key={k}><h3>{k}</h3><section>{v.map(x=><button key={x} className={cn(sel.includes(x)&&"on")} onClick={()=>toggle(x)}>{x}</button>)}</section></div>)}</div></>}
   {step===1&&<><Top title="SCENE MATCH" desc={`${sel.join(" + ")} 조건과 실제 장면 메타데이터를 비교했습니다.`}/><button className="ghost back" onClick={()=>setStep(0)}><ArrowLeft/>검색 조건 수정</button><div className="results">{ranked.map(({scene:s,score},i)=><article key={s.id}><strong className="rank">0{i+1}</strong><div className="result-main"><Badge s={s.status}/><small>{s.type} · {s.year} · {s.genres.join(" / ")}</small><h2>{s.work} <i>{s.original}</i></h2><h3>{s.title}</h3><p>{s.description}</p><div className="match">{hits(s,sel).map(x=><span key={x}><Check/>{x}</span>)}</div><div className="reason"><b>추천 이유</b> · {hits(s,sel).join(", ")||"장르 유사성"}이 장면 메타데이터와 일치합니다.{s.status==="PARTIAL"&&" 장면 단위 출처는 추가 검토가 필요합니다."}</div></div><div className="score"><b>{score}%</b><span>MATCH</span><button onClick={()=>{setPicked(s);setStep(2)}}>명장면 확인</button><a href={s.source} target="_blank">{s.sourceLabel}</a></div></article>)}</div></>}
   {step===2&&picked&&<><Top title="원작 느낌과 재해석 스타일" desc={`${picked.work} · ${picked.title}의 SCENE DNA를 창작 파라미터로 변환합니다.`}/><div className="two"><Panel><Badge s={picked.status}/><h2>{picked.title}</h2><p>{picked.description}</p><h3>SCENE DNA</h3><div className="dna">{[...picked.emotion,...picked.weather,...picked.props,...picked.action,...picked.direction].map(x=><span key={x}>{x}</span>)}</div><div className="notice"><ShieldCheck/>대사·세트·화면을 복제하지 않고 감정, 상황, 상징만 창작 재료로 사용합니다.</div></Panel><Panel><p className="eyebrow">ORIGINAL FEEL</p><div className="feel"><h2>{feel}%</h2><span>{feel>66?"강한 오마주":feel>33?"균형 재해석":"자유 패러디"}</span></div><input type="range" min="0" max="100" value={feel} onChange={e=>setFeel(+e.target.value)}/><div className="range-label"><span>자유 패러디</span><span>강한 오마주</span></div><h3>재해석 스타일</h3><div className="styles">{styles.map(x=><button key={x} className={cn(style===x&&"on")} onClick={()=>setStyle(x)}>{x}</button>)}</div></Panel></div><Actions back={()=>setStep(1)} next={()=>setStep(3)}/></>}
   {step===3&&<><Top title="캐릭터와 팬 개인화" desc="이 정보는 최종 대사와 소품 문구에 반영됩니다."/><div className="two"><Panel><h2>CHARACTER PERSONA</h2><Field label="캐릭터 이름" value={char} set={setChar}/><Field label="말투" value="다정하고 장난기 있는 반말"/><Field label="팬 호칭" value="우리 팬"/><Field label="금지 표현" value="과도한 비하, 실명 언급"/></Panel><Panel><h2>FAN PERSONALIZE</h2><Field label="팬 닉네임" value={fan} set={setFan}/><Field label="둘만의 밈" value="비 오는 날에도 출석"/><Field label="특별 요청" value="마지막 컷에 감사 인사"/><label>컷 구성</label><div className="styles cuts">{[4,6].map(n=><button key={n} className={cn(cut===n&&"on")} onClick={()=>setCut(n as 4|6)}>{n}컷</button>)}</div></Panel></div><Actions back={()=>setStep(2)} next={()=>{if(picked)setLines(makeStory(picked,style,feel,fan,char,cut).lines);setStep(4)}} label="STORY 생성"/></>}
   {step===4&&story&&<><Top title="AI STORY ENGINE" desc="검증된 장면을 여러 편집 단계로 분리해 최종 후보를 평가합니다."/><div className="warning"><WandSparkles/><div><b>AI provider 미연결</b><p>현재 결과는 연결 상태를 속이지 않는 규칙 기반 Vertical Slice입니다. 실제 API 연결 시 동일한 단계별 adapter를 사용합니다.</p></div></div><div className="two engine"><Panel><h2>ENGINE PIPELINE</h2>{["ORIGINAL SCENE ANALYZER","SCENE DNA","IDEA ROOM · 10개","STORY JUDGE","STORY DIRECTOR","SCREENWRITER","DIALOGUE EDITOR","CHARACTER EDITOR","PARODY EDITOR","ORIGINALITY CHECK","QUALITY CHECK"].map((x,i)=><div className="stage" key={x}><span><Check/></span><b>{x}</b><small>{i<2?"로컬 분석":"규칙 기반"}</small></div>)}</Panel><Panel><p className="eyebrow">FINAL CANDIDATE 01</p><h2 className="story-title">{story.title}</h2><p>{story.logline}</p><div className="script">{story.lines.map((x,i)=><div key={i}><span>{i+1}</span><p>{x}</p></div>)}</div><div className="metrics">{Object.entries(story.quality).map(([k,v])=><div key={k}><span>{k}</span><b>{v}</b></div>)}</div></Panel></div><Actions back={()=>setStep(3)} next={()=>setStep(5)} label="편집기로 이동"/></>}
   {step===5&&story&&<><Top title={`${cut}컷 SCENE EDITOR`} desc="각 컷의 대사와 장면 지시를 수정하고, 권장 SCENE KIT을 확인하세요."/><div className="editor"><div className="cut-grid">{lines.map((x,i)=><article className="cut" key={i}><SceneCard text={x} i={i}/><textarea value={x} onChange={e=>setLines(a=>a.map((v,j)=>j===i?e.target.value:v))}/></article>)}</div><Panel><p className="eyebrow">AUTO MATCHED</p><h2>RAIN ROMANCE KIT</h2><div className="kit">{[["Background","야간 거리 · 젖은 도로"],["Foreground","빗방울 · 약한 보케"],["Main Prop","투명 우산"],["Lighting","가로등 림 라이트"],["Camera","Medium Close-up"],["Shadow","Contact Shadow"]].map(([a,b])=><p key={a}><span>{a}</span><b>{b}</b></p>)}</div><div className="quality"><Gauge/><p><b>품질 경고 1개</b><br/>Warudo 캐릭터 광원을 왼쪽 후면으로 맞춰 주세요.</p></div><button className="upload"><Upload/>Warudo 자료 업로드</button><small>V1은 직접 제어 없이 업로드·태그 방식입니다.</small></Panel></div><Actions back={()=>setStep(4)} next={()=>setStep(6)} label="완성작 확인"/></>}
   {step===6&&story&&picked&&<><Top title="완성작" desc="Vertical Slice의 전체 제작 흐름이 완료되었습니다."/><div className="success"><BadgeCheck/><div><b>{story.title}</b><p>{picked.work}의 검증 장면에서 시작해 {lines.length}컷 방셀로 재해석했습니다.</p></div></div><div className="finish"><Panel><div className="cut-grid">{lines.map((x,i)=><SceneCard key={i} text={x} i={i}/>)}</div></Panel><Panel><button onClick={save}><Save/>프로젝트 저장</button><button onClick={()=>navigator.clipboard.writeText(story.title).then(()=>note("제목을 복사했습니다."))}><Copy/>제목 복사</button><button onClick={()=>navigator.clipboard.writeText(lines.join("\n\n")).then(()=>note("본문을 복사했습니다."))}><Copy/>본문 복사</button><button disabled><Download/>전체 다운로드 <small>출력 엔진 미연결</small></button><button disabled><Mic/>음성 링크 <small>녹음 없음</small></button><div className="soop"><b>SOOP 게시 순서</b><ol><li>장면 미디어 다운로드</li><li>제목 복사</li><li>본문 복사</li><li>SOOP 게시판에 붙여넣기</li></ol></div></Panel></div><button className="ghost back" onClick={()=>setStep(5)}><ArrowLeft/>편집기로 돌아가기</button></>}
  </section></div>{toast&&<div className="toast"><Check/>{toast}</div>}</main>
}
function Top({title,desc}:{title:string;desc:string}){return <div className="top"><p className="eyebrow">BANGSEL PRODUCTION</p><h1>{title}</h1><p>{desc}</p></div>}
function Badge({s}:{s:Status}){return <span className={cn("badge",s.toLowerCase())}>{s==="VERIFIED"?<BadgeCheck/>:<ShieldCheck/>}{s}</span>}
function Panel({children}:{children:React.ReactNode}){return <section className="panel">{children}</section>}
function Field({label,value,set}:{label:string;value:string;set?:(x:string)=>void}){return <label className="field">{label}<input value={value} readOnly={!set} onChange={e=>set?.(e.target.value)}/></label>}
function Actions({back,next,label="다음 단계"}:{back:()=>void;next:()=>void;label?:string}){return <div className="actions"><button className="ghost" onClick={back}><ArrowLeft/>이전</button><button className="primary" onClick={next}>{label}<ArrowRight/></button></div>}
function SceneCard({text,i}:{text:string;i:number}){return <div className="scene-card"><span>CUT {i+1}</span><div><Film/></div><p>{text}</p></div>}

export default function Page(){return <Studio scenes={db}/>}
